name: musa
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.2
  music_player: ^0.1.5
  flare_splash_screen: ^3.0.1
  flutter_radio: ^0.1.8
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.3
  google_sign_in: ^4.5.5
  cloud_firestore: ^0.14.1+3
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - mini.flr
    - splash.flr
    - logo.png
    - back.png
    - disk.png
    - back.jpg
    - back1.jpg
    - headphone.jpg

  fonts:
    - family: KaushanScript
      fonts:
        - asset: fonts/KaushanScript-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf


